name: Build Check

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build-x86:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: build-deps
        uses: ./.github/actions/build-install-deps
      - name: Build emulator ${{ steps.build-deps.outputs.vortex-version }}
        run: make DEBUG=1 TIMER_DEBUG=1 TIMER_DEBUG_LISTS=1
  build-arm:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: build-deps
        uses: ./.github/actions/build-install-deps
      - name: Build emulator ${{ steps.build-deps.outputs.vortex-version }}
        run: make DEBUG=1 TIMER_DEBUG=1 TIMER_DEBUG_LISTS=1

  