name: vortex-build-x64

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  workflow_call:
    outputs:
      artifact-url:
        description: "Artifact URL"
        value: ${{ jobs.build.outputs.output1 }}
      artifact-id:
        description: "Artifact ID"
        value: ${{ jobs.build.outputs.output2 }}
      artifact-digest:
        description: "Artifact Digest SHA"
        value: ${{ jobs.build.outputs.output3 }}
      vortex-version:
        description: "Version of the artifact"
        value: ${{ jobs.build.outputs.output4 }}
      build-arch:
        description: "Build architecture"
        value: ${{ jobs.build.outputs.output5 }}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.upload-artifact.outputs.artifact-url }}
      output2: ${{ steps.upload-artifact.outputs.artifact-id }}
      output3: ${{ steps.upload-artifact.outputs.artifact-digest }}
      output4: ${{ steps.build-deps.outputs.vortex-version }}
      output5: ${{ steps.build-deps.outputs.vortex-arch }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
          fetch-tags: true
      - id: build-deps
        uses: ./.github/actions/build-install-deps
      - name: Build emulator ${{ steps.build-deps.outputs.vortex-version }}
        run: make package
      - name: Upload asset
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: vortex-${{ steps.build-deps.outputs.vortex-version }}-${{ steps.build-deps.outputs.vortex-arch }}
          path: vortex-${{ steps.build-deps.outputs.vortex-version }}-${{ steps.build-deps.outputs.vortex-arch }}.tar.bz2